### ISSUE TITLE
Pagination warning

### ISSUE THREAD

**Issue by star4z** [star4z/familytree#53]
I keep getting the following warning:

UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'webapp.models.Person'> QuerySet.

More info here:
https://stackoverflow.com/questions/44033670/python-django-rest-framework-unorderedobjectlistwarning/44036414

It looks like the Person class may need an ordering.

**Comment by cynthia5610** [comment]
Added ordering = ['id'] to the ListViews to get rid of Pagination Warning.
